// gen-index — regenerate rules/README.md from rule frontmatter.
// The index is generated, never hand-edited: this is what ends count-drift.
// Views: by family (tier 1), by concern (tier 2), and a backlog of non-canonical rules.
// Zero dependencies.

import { readFileSync, writeFileSync } from 'node:fs';
import { basename, relative, sep } from 'node:path';
import { parseYaml, listRuleFiles, RULES_DIR } from './yaml-lite.mjs';

const FAMILIES = ['0-foundations', '1-observability', '2-application-flow', '3-infra', '4-edge'];
const CONCERNS = ['architecture', 'domain', 'persistence', 'edge', 'testing', 'style', 'process'];

const rules = [];
for (const file of listRuleFiles()) {
  const r = parseYaml(readFileSync(file, 'utf8'));
  r._path = relative(RULES_DIR, file).split(sep).join('/');
  r._id = r.id || basename(file, '.yaml');
  rules.push(r);
}

const badge = (r) => `${r.severity || '?'} · ${r.status || '?'}`;
const row = (r) => `- [\`${r._id}\`](${r._path}) — ${r.title || ''} _(${badge(r)})_`;

const out = [];
out.push('# Rules index');
out.push('');
out.push('> Generated by `tooling/gen-index.mjs` — do not edit by hand.');
out.push('');
out.push(`${rules.length} rule(s). Schema in [_schema.md](_schema.md); model and workflow in [rules-guide.md](rules-guide.md).`);
out.push('');

// Tier 1 — framework, by family -> package
out.push('## Tier 1 — Framework (per package)');
out.push('');
const fw = rules.filter((r) => r.tier === 'framework');
for (const fam of FAMILIES) {
  const inFam = fw.filter((r) => r.family === fam);
  if (!inFam.length) continue;
  out.push(`### ${fam}`);
  out.push('');
  const byPkg = new Map();
  for (const r of inFam) {
    const k = r.package || '(unknown)';
    if (!byPkg.has(k)) byPkg.set(k, []);
    byPkg.get(k).push(r);
  }
  for (const [pkg, list] of [...byPkg.entries()].sort()) {
    out.push(`**${pkg}**`);
    out.push('');
    for (const r of list.sort((a, b) => a._id.localeCompare(b._id))) out.push(row(r));
    out.push('');
  }
}

// Tier 2 — conventions, by concern
out.push('## Tier 2 — Conventions (per concern)');
out.push('');
const conv = rules.filter((r) => r.tier === 'convention');
for (const c of CONCERNS) {
  const inC = conv.filter((r) => r.concern === c);
  if (!inC.length) continue;
  out.push(`### ${c}`);
  out.push('');
  for (const r of inC.sort((a, b) => a._id.localeCompare(b._id))) out.push(row(r));
  out.push('');
}

// Backlog — anything not canonical
const backlog = rules.filter((r) => r.status && r.status !== 'canonical');
out.push('## Review backlog (status != canonical)');
out.push('');
if (!backlog.length) out.push('_None._');
else for (const r of backlog.sort((a, b) => (a.status + a._id).localeCompare(b.status + b._id))) {
  out.push(`- [\`${r._id}\`](${r._path}) — **${r.status}** — ${r.title || ''}`);
}
out.push('');

writeFileSync(`${RULES_DIR}/README.md`, out.join('\n'));
console.log(`gen-index: wrote README.md (${rules.length} rule(s), ${backlog.length} in backlog).`);
